### ISSUE TITLE
Problem to use mem_trace for Optix SDK examples

### ISSUE THREAD

**Issue by brad-mengchi** [NVlabs/NVBit#13] opened 2020-03-13 12:57 UTC
Hello,

I try to use mem_trace for Optix SDK examples(optixHello, optixRaycasting), however, I found the program hangs after optixLaunch() API on CUDA_SYNC_CHECK(cudaDeviceSynchronize inside).

Then I try to change mem_trace and find out if I comment out "channel_dev.push(&ma, sizeof(mem_access_t));" inside instrument_mem(), the program will not hang.

So does NVbit ChannelDev not work for optix apps?

Thanks!

**Comment by ovilla** [comment] 2020-10-14 20:10
Tried this example since I got to test Optix version 7.0 for bug #28 and all seems to work with NVBit version 1.5.

An important observation is that optixHello in particular does not launch "User visible Kernels" but only "NVIDIA Internal" kernels which by design are not  exposed in NVBit. Paraphs this was confusing earlier versions of NVBit?

However, the current NVBit v1.5 mem_trace.so works fine with optixHello (i.e. does not produce any output since only "NVIDIA Internal" kernels are launched) and works as expected with optixCurvers (prints some memory accessed patterns for each launched kernel).

Closing this issue for now. Please reopen with more information if issue is still there.

**Closed by ovilla** 2020-10-14 20:10 UTC
